import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.scss";
import Header from "./pageComponents/Header/Header";
import Footer from "./pageComponents/Footer/Footer";

const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  getcall,
  auth,
  reg,
}: Readonly<{
  children: React.ReactNode;
  getcall: React.ReactNode;
  auth: React.ReactNode;
  reg: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} main_content`}>
        <Header />
        {getcall}
        {auth}
        {reg}
        {children}

        <Footer />
      </body>
    </html>
  );
}
