import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.scss";
import Header from "./pageComponents/Header/Header";
import Footer from "./pageComponents/Footer/Footer";
import useSWR from "swr";
import { getData } from "./reducers/mainPageredcer";
import PageProvider from "./pageComponents/PageProvider/PageProvider";
const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} main_content`}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
